version: 2

jobs:
  deploy_dev: # ジョブ名
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: yarn install
          command: yarn install
      # - run:
      #     name: 'Install Dependecies'
      #     command: yarn lint
      - run:
          name: 'build'
          command: yarn run build
      - run:
          name: 'install firebase-tools'
          command: yarn add --dev firebase-tools
      - run:
          name: 'deploy to firebase'
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy_dev: # ワークフローの名前
    jobs:
      - deploy_dev: # 上で定義したジョブを指定します
          context: FIREBASE_TOKEN
          filters:
            branches:
              only: master # masterブランチのみを実行対象とします